export const Movies = [
  {
    name: "Алтышка",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "1a.jpg",
    image: "1.jpg",
    category: "вестерн",
    language: "English",
    year: "2022",
    time: "3hr",
    video: "",
    rate: 3.4,
    reviews: 23,
  },
  {
    name: "БирКунТун",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "22.jpg",
    image: "2.jpg",
    category: "Триллер",
    language: "Kyrgyz",
    year: "1999",
    time: "4hr",
    video: "",
    rate: 5,
    reviews: 100,
  },
  {
    name: "Агай",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "33.jpg",
    image: "3.jpg",
    category: "Приключение",
    language: "Kyrgyz",
    year: "2000",
    time: "11hr",
    video: "",
    rate: 2.5,
    reviews: 2,
  },
  {
    name: "Адам Болчу",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "44.jpg",
    image: "4.jpg",
    category: "Мюзиклы",
    language: "Kyrgyz",
    year: "2022",
    time: "5hr",
    video: "",
    rate: 1.5,
    reviews: 6,
  },
  {
    name: "Эсимде",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "55.jpg",
    image: "5.jpg",
    category: "Романтический",
    language: "Kyrgyz",
    year: "1899",
    time: "1hr",
    video: "",
    rate: 5,
    reviews: 56,
  },
  {
    name: "Буюрса",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "66.jpg",
    image: "6.jpg",
    category: "Ужастик",
    language: "Swahili",
    year: "2012",
    time: "19hr",
    video: "",
    rate: 4.5,
    reviews: 34,
  },
  {
    name: "Эрмен Жыты",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "77.jpg",
    image: "7.jpg",
    category: "Фантазия",
    language: "Korean",
    year: "2005",
    time: "4hr",
    video: "",
    rate: 0,
    reviews: 0,
  },
  {
    name: "Эшбай",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "88.jpg",
    image: "8.jpg",
    category: "Виды спорта",
    language: "Japanese",
    year: "1999",
    time: "6hr",
    video: "",
    rate: 0.5,
    reviews: 0,
  },
  {
    name: "Здравствуй, ПАПА!",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "9.jpg",
    image: "9.jpg",
    category: "Драма",
    language: "Swahili",
    year: "2012",
    time: "4hr",
    video: "",
    rate: 1,
    reviews: 1,
  },
  {
    name: "Сагынбай Манасчы",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "10.jpg",
    image: "10.jpg",
    category: "комедия",
    language: "French",
    year: "2000",
    time: "1hr",
    video: "",
    rate: 0,
    reviews: 4,
  },
  {
    name: "Баарын кайрадан БАШЬАЙЛЫЧЫ",
    desc: "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
    titleImage: "11.webp",
    image: "11.jpg",
    category: "Действие",
    language: "Chinese",
    year: "2012",
    time: "9hr",
    video: "",
    rate: 1,
    reviews: 6,
  },
  {
    name: "Наркобарон ",
    desc: "Наркобарон хочет уйти на покой, но криминальный мир не отпускает. Успешное возвращение Гая Ричи к корням",
    titleImage: "12.webp",
    image: "12.jpg",
    category: "Action",
    language: "Chinese",
    year: "2019",
    time: "2hr",
    video: "",
    rate: 1,
    reviews: 3,
  },
  {
    name: "Триггер",
    desc: "Страшная трагедия вынуждает психолога-провокатора вернуться к практике. Напряженная драма с Максимом Матвеевым",
    titleImage: "13.webp",
    image: "13.jpg",
    category: "Drama",
    language: "Chinese",
    year: "2016",
    time: "4hr",
    video: "",
    rate: 3,
    reviews: 8,
  },
  {
    name: "БЕСПРИНЦИПНЫЕ",
    desc: "Смешные истории из жизни очень богатых москвичей. Продолжение комедии по мотивам рассказов Александра Цыпкина",
    titleImage: "14.webp",
    image: "14.jpg",
    category: "Lonely",
    language: "Rus",
    year: "2020",
    time: "9hr",
    video: "",
    rate: 1,
    reviews: 6,
  },
  {
    name: "МАЖОР В СОЧИ",
    desc: "Как изменить жизнь и защитить ребенка, если привык решать проблемы силой? Душевный экшен с Павлом Прилучным",
    titleImage: "15.webp",
    image: "15.jpg",
    category: "Drama",
    language: "Chinese",
    year: "2022",
    time: "12hr",
    video: "",
    rate: 1,
    reviews: 6,
  },
];

export const UsersData = [
  {
    fullName: "Эмиль Эсеналиев",
    image: "c1.png",
    email: "tomcruise@gmail.com",
    rate: 4.5,
    message:
      "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
  },
  {
    fullName: "Азиз Бейшеналиев",
    image: "c2.png",
    email: "emilyblunt@gmail.com",
    rate: 0.5,
    message:
      "There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
  },
  {
    fullName: "Анвар Осмоналиев",
    image: "c3.png",
    email: "johnsnow@gmail.com",
    rate: 2.5,
    message: "The majority have suffered alteration.",
  },
  {
    fullName: "Динара Джумабаева",
    image: "c4.png",
    email: "willsmith@gmail.com",
    rate: 5,
    message:
      "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
  },
  {
    fullName: "Адилет Усубалиев",
    email: "minahlee@gmail.com",
    image: "c5.png",
    rate: 1.5,
    message:
      "Lorem ipsum dolor sit amet, consecetur adipiscing elseddo eiusmod There are many variations of passages of lorem Ipsum available, but the majority have suffered alteration.",
  },
];
